server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: springcloud-feign
  thymeleaf:
    cache: false
    check-template: true
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
