server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t_user?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  application:
    name: springcloud-server

mybatis:
  mapper-locations: classpath:mybatis/*.xml
